# Form implementation generated from reading ui file 'Home.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/desktopIcon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    border:none;\n"
"\n"
"}")
        MainWindow.setIconSize(QtCore.QSize(31, 24))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    background-color: qlineargradient(\n"
"         y1: 0, x1: 0, y2: 1, x2: 0,\n"
"         stop: 0 #78B3CE, \n"
"         stop: 1 #D5EDF8\n"
"    );\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sideNav = QtWidgets.QFrame(parent=self.centralwidget)
        self.sideNav.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sideNav.sizePolicy().hasHeightForWidth())
        self.sideNav.setSizePolicy(sizePolicy)
        self.sideNav.setMinimumSize(QtCore.QSize(320, 694))
        self.sideNav.setStyleSheet("#sideNav{\n"
"    background-color:white;\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"}")
        self.sideNav.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.sideNav.setObjectName("sideNav")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sideNav)
        self.verticalLayout_2.setContentsMargins(-1, 29, -1, 40)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PetmateLogo = QtWidgets.QLabel(parent=self.sideNav)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PetmateLogo.sizePolicy().hasHeightForWidth())
        self.PetmateLogo.setSizePolicy(sizePolicy)
        self.PetmateLogo.setMinimumSize(QtCore.QSize(212, 81))
        self.PetmateLogo.setMaximumSize(QtCore.QSize(212, 81))
        self.PetmateLogo.setText("")
        self.PetmateLogo.setPixmap(QtGui.QPixmap(":/Images/image/petmateLogo.png"))
        self.PetmateLogo.setScaledContents(True)
        self.PetmateLogo.setObjectName("PetmateLogo")
        self.verticalLayout_2.addWidget(self.PetmateLogo, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.Buttons = QtWidgets.QFrame(parent=self.sideNav)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Buttons.sizePolicy().hasHeightForWidth())
        self.Buttons.setSizePolicy(sizePolicy)
        self.Buttons.setMinimumSize(QtCore.QSize(240, 260))
        self.Buttons.setMaximumSize(QtCore.QSize(240, 260))
        self.Buttons.setStyleSheet("QFrame{\n"
"    background-color:transparent;\n"
"}")
        self.Buttons.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.Buttons.setObjectName("Buttons")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Buttons)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.homeBtn = QtWidgets.QToolButton(parent=self.Buttons)
        self.homeBtn.setMinimumSize(QtCore.QSize(240, 0))
        self.homeBtn.setAutoFillBackground(False)
        self.homeBtn.setStyleSheet("QToolButton{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    font: 87 12pt \"Montserrat Black\";\n"
"    font-weight:bold;\n"
"    color:#78B3CE;\n"
"    border-radius:15px;\n"
"    padding:10;\n"
"}\n"
"QToolButton:hover{\n"
"    background-color: rgb(255, 241, 206);\n"
"\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.homeBtn.setIcon(icon1)
        self.homeBtn.setIconSize(QtCore.QSize(25, 25))
        self.homeBtn.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.homeBtn.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.homeBtn.setAutoRaise(False)
        self.homeBtn.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.homeBtn.setObjectName("homeBtn")
        self.verticalLayout.addWidget(self.homeBtn)
        self.addPatientBtn = QtWidgets.QToolButton(parent=self.Buttons)
        self.addPatientBtn.setMinimumSize(QtCore.QSize(240, 0))
        self.addPatientBtn.setAutoFillBackground(False)
        self.addPatientBtn.setStyleSheet("QToolButton{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    font: 87 12pt \"Montserrat Black\";\n"
"    font-weight:bold;\n"
"    color:#78B3CE;\n"
"    border-radius:15px;\n"
"    padding:10;\n"
"}\n"
"QToolButton:hover{\n"
"    background-color: rgb(255, 241, 206);\n"
"\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/AddIcon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.addPatientBtn.setIcon(icon2)
        self.addPatientBtn.setIconSize(QtCore.QSize(25, 25))
        self.addPatientBtn.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.addPatientBtn.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.addPatientBtn.setAutoRaise(False)
        self.addPatientBtn.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.addPatientBtn.setObjectName("addPatientBtn")
        self.verticalLayout.addWidget(self.addPatientBtn)
        self.petRecordsBtn = QtWidgets.QToolButton(parent=self.Buttons)
        self.petRecordsBtn.setMinimumSize(QtCore.QSize(240, 0))
        self.petRecordsBtn.setAutoFillBackground(False)
        self.petRecordsBtn.setStyleSheet("QToolButton{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    font: 87 12pt \"Montserrat Black\";\n"
"    font-weight:bold;\n"
"    color:#78B3CE;\n"
"    border-radius:15px;\n"
"    padding:10;\n"
"}\n"
"QToolButton:hover{\n"
"    background-color: rgb(255, 241, 206);\n"
"\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/petDetailsIcon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.petRecordsBtn.setIcon(icon3)
        self.petRecordsBtn.setIconSize(QtCore.QSize(25, 25))
        self.petRecordsBtn.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.petRecordsBtn.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.petRecordsBtn.setAutoRaise(False)
        self.petRecordsBtn.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.petRecordsBtn.setObjectName("petRecordsBtn")
        self.verticalLayout.addWidget(self.petRecordsBtn)
        self.appointmentBtn = QtWidgets.QToolButton(parent=self.Buttons)
        self.appointmentBtn.setMinimumSize(QtCore.QSize(240, 0))
        self.appointmentBtn.setAutoFillBackground(False)
        self.appointmentBtn.setStyleSheet("QToolButton{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    font: 87 12pt \"Montserrat Black\";\n"
"    font-weight:bold;\n"
"    color:#78B3CE;\n"
"    border-radius:15px;\n"
"    padding:10;\n"
"}\n"
"QToolButton:hover{\n"
"    background-color: rgb(255, 241, 206);\n"
"\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Icons/AppointmentIcon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.appointmentBtn.setIcon(icon4)
        self.appointmentBtn.setIconSize(QtCore.QSize(25, 25))
        self.appointmentBtn.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.appointmentBtn.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.appointmentBtn.setAutoRaise(False)
        self.appointmentBtn.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.appointmentBtn.setObjectName("appointmentBtn")
        self.verticalLayout.addWidget(self.appointmentBtn)
        self.verticalLayout_2.addWidget(self.Buttons, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=self.sideNav)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(220, 220))
        self.label.setMaximumSize(QtCore.QSize(220, 220))
        self.label.setStyleSheet("QLabel{\n"
"    margin-bottom:47pc;\n"
"\n"
"}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Images/image/navImg.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.toolButton = QtWidgets.QToolButton(parent=self.sideNav)
        self.toolButton.setMinimumSize(QtCore.QSize(240, 0))
        self.toolButton.setStyleSheet("QToolButton{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    font: 87 12pt \"Montserrat Black\";\n"
"    font-weight:bold;\n"
"    color:#78B3CE;\n"
"    border-radius:15px;\n"
"    padding:10;\n"
"}\n"
"QToolButton:hover{\n"
"    background-color: rgb(255, 241, 206);\n"
"\n"
"}")
        self.toolButton.setText("       LOG OUT")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Icons/logOutIcon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton.setIcon(icon5)
        self.toolButton.setIconSize(QtCore.QSize(30, 30))
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.toolButton.setObjectName("toolButton")
        self.verticalLayout_2.addWidget(self.toolButton, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.horizontalLayout_3.addWidget(self.sideNav)
        self.MainContent = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainContent.sizePolicy().hasHeightForWidth())
        self.MainContent.setSizePolicy(sizePolicy)
        self.MainContent.setStyleSheet("#MainContent{\n"
"    background-color:white;\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"}")
        self.MainContent.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.MainContent.setObjectName("MainContent")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.MainContent)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.MainContent)
        self.stackedWidget.setStyleSheet("QStackedWidget{\n"
"    background:transparent;\n"
"\n"
"}")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.homepage = QtWidgets.QWidget()
        self.homepage.setStyleSheet("QWidget{\n"
"    background:transparent;\n"
"\n"
"}")
        self.homepage.setObjectName("homepage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.homepage)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.home = QtWidgets.QFrame(parent=self.homepage)
        self.home.setStyleSheet("QFrame{\n"
"    background:transparent;\n"
"\n"
"}")
        self.home.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.home.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.home.setObjectName("home")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.home)
        self.verticalLayout_8.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame = QtWidgets.QFrame(parent=self.home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 250))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame.setStyleSheet("QFrame{\n"
"    background:transparent;\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setObjectName("frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_7.setContentsMargins(45, -1, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.welcome = QtWidgets.QFrame(parent=self.frame)
        self.welcome.setStyleSheet("QFrame{\n"
"    background:transparent;\n"
"\n"
"}")
        self.welcome.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.welcome.setObjectName("welcome")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.welcome)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(parent=self.welcome)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_7.setStyleSheet("QLabel{\n"
"    font: 81 32pt \"Montserrat ExtraBold\";\n"
"    color: #272727;\n"
"    text-align:left;\n"
"}\n"
"")
        self.label_7.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_8 = QtWidgets.QLabel(parent=self.welcome)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 80))
        self.label_8.setStyleSheet("QLabel{\n"
"    \n"
"    font: 25 14pt \"Montserrat Light\";\n"
"    color: #2A2A2A;\n"
"}\n"
"\n"
"")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.horizontalLayout_7.addWidget(self.welcome, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.picture = QtWidgets.QFrame(parent=self.frame)
        self.picture.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.picture.setObjectName("picture")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.picture)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(parent=self.picture)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(285, 285))
        self.label_9.setMaximumSize(QtCore.QSize(285, 285))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/Images/image/image 1.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.horizontalLayout_7.addWidget(self.picture)
        self.verticalLayout_8.addWidget(self.frame)
        self.Appointment = QtWidgets.QFrame(parent=self.home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Appointment.sizePolicy().hasHeightForWidth())
        self.Appointment.setSizePolicy(sizePolicy)
        self.Appointment.setMinimumSize(QtCore.QSize(0, 0))
        self.Appointment.setStyleSheet("QFrame{\n"
"    background:transparent;\n"
"\n"
"}")
        self.Appointment.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.Appointment.setObjectName("Appointment")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Appointment)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.appointment_date = QtWidgets.QFrame(parent=self.Appointment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appointment_date.sizePolicy().hasHeightForWidth())
        self.appointment_date.setSizePolicy(sizePolicy)
        self.appointment_date.setMinimumSize(QtCore.QSize(735, 62))
        self.appointment_date.setMaximumSize(QtCore.QSize(735, 62))
        self.appointment_date.setStyleSheet("QFrame{\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color: #81BFDA;\n"
"\n"
"}")
        self.appointment_date.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.appointment_date.setObjectName("appointment_date")
        self.gridLayout = QtWidgets.QGridLayout(self.appointment_date)
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtWidgets.QLabel(parent=self.appointment_date)
        self.label_10.setStyleSheet("QLabel{\n"
"    color:black;\n"
"    font: 81 26pt \"Montserrat ExtraBold\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_6.addWidget(self.appointment_date, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.upcoming_appointment = QtWidgets.QTableWidget(parent=self.Appointment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upcoming_appointment.sizePolicy().hasHeightForWidth())
        self.upcoming_appointment.setSizePolicy(sizePolicy)
        self.upcoming_appointment.setMinimumSize(QtCore.QSize(0, 300))
        self.upcoming_appointment.setStyleSheet("QTableWidget {\n"
"    background-color: white;\n"
"    border: none;\n"
"    gridline-color: transparent;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"    border-radius: 10px; \n"
"    text-align: center;\n"
"    qproperty-alignment: AlignCenter;\n"
"    color: #272727;\n"
"}\n"
"QTableWidget::item {\n"
"    padding:30px;\n"
"    margin-bottom:15px;\n"
"    background-color: #EFEFEF;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: transparent;\n"
"    color: #272727;\n"
"    font: 87 16pt \"Montserrat Black\";\n"
"    padding: 8px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    word-wrap: break-word;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    word-wrap: break-word;\n"
"    padding: 8px;\n"
"    background: #F5F5F5;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    word-wrap: normal;\n"
"}\n"
"\n"
"\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: white; \n"
"    width: 8px; \n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #81BFDA; /* Scrollbar color */\n"
"    min-height: 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #2980b9; \n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical, \n"
"QScrollBar::sub-line:vertical, \n"
"QScrollBar::up-arrow:vertical, \n"
"QScrollBar::down-arrow:vertical, \n"
"QScrollBar::add-page:vertical, \n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"    height: 0px;\n"
"}\n"
"")
        self.upcoming_appointment.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.upcoming_appointment.setAutoScrollMargin(15)
        self.upcoming_appointment.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.upcoming_appointment.setTabKeyNavigation(False)
        self.upcoming_appointment.setProperty("showDropIndicator", False)
        self.upcoming_appointment.setDragDropOverwriteMode(False)
        self.upcoming_appointment.setAlternatingRowColors(False)
        self.upcoming_appointment.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.upcoming_appointment.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.upcoming_appointment.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.upcoming_appointment.setShowGrid(False)
        self.upcoming_appointment.setGridStyle(QtCore.Qt.PenStyle.NoPen)
        self.upcoming_appointment.setWordWrap(True)
        self.upcoming_appointment.setCornerButtonEnabled(False)
        self.upcoming_appointment.setRowCount(0)
        self.upcoming_appointment.setObjectName("upcoming_appointment")
        self.upcoming_appointment.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.upcoming_appointment.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.upcoming_appointment.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.upcoming_appointment.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.upcoming_appointment.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.upcoming_appointment.setHorizontalHeaderItem(4, item)
        self.upcoming_appointment.horizontalHeader().setCascadingSectionResizes(False)
        self.upcoming_appointment.horizontalHeader().setDefaultSectionSize(140)
        self.upcoming_appointment.horizontalHeader().setMinimumSectionSize(50)
        self.upcoming_appointment.horizontalHeader().setSortIndicatorShown(False)
        self.upcoming_appointment.horizontalHeader().setStretchLastSection(True)
        self.upcoming_appointment.verticalHeader().setVisible(False)
        self.upcoming_appointment.verticalHeader().setHighlightSections(False)
        self.upcoming_appointment.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_6.addWidget(self.upcoming_appointment)
        self.verticalLayout_8.addWidget(self.Appointment)
        self.verticalLayout_7.addWidget(self.home)
        self.stackedWidget.addWidget(self.homepage)
        self.AddpatientPage = QtWidgets.QWidget()
        self.AddpatientPage.setStyleSheet("QWidget{\n"
"    background:transparent;\n"
"\n"
"}")
        self.AddpatientPage.setObjectName("AddpatientPage")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.AddpatientPage)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_2 = QtWidgets.QFrame(parent=self.AddpatientPage)
        self.frame_2.setStyleSheet("QFrame{\n"
"    background:transparent;\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_11.setContentsMargins(0, 0, 9, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.AddpatientStack = QtWidgets.QStackedWidget(parent=self.frame_2)
        self.AddpatientStack.setObjectName("AddpatientStack")
        self.InputPage = QtWidgets.QWidget()
        self.InputPage.setObjectName("InputPage")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.InputPage)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.InputPage)
        self.scrollArea.setStyleSheet("QScrollBar:vertical {\n"
"    border: none;\n"
"    background: white; \n"
"    width: 8px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #81BFDA; /* Scrollbar color */\n"
"    max-height: 15px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #2980b9; \n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical, \n"
"QScrollBar::sub-line:vertical, \n"
"QScrollBar::up-arrow:vertical, \n"
"QScrollBar::down-arrow:vertical, \n"
"QScrollBar::add-page:vertical, \n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"    height: 0px;\n"
"}")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 849, 820))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.frame_4 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_5)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_3.setMinimumSize(QtCore.QSize(735, 62))
        self.frame_3.setMaximumSize(QtCore.QSize(735, 62))
        self.frame_3.setStyleSheet("QFrame{\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color: #81BFDA;\n"
"\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_3.setStyleSheet("QLabel{\n"
"    color:black;\n"
"    font: 81 26pt \"Montserrat ExtraBold\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_2.setMinimumSize(QtCore.QSize(30, 30))
        self.label_2.setMaximumSize(QtCore.QSize(30, 30))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Icons/Icons/UserIcon.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout_28.addWidget(self.frame_3)
        self.verticalLayout_27.addWidget(self.frame_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.DetailsInput = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_5)
        self.DetailsInput.setStyleSheet("QLabel{\n"
"    color:balack;\n"
"}\n"
"QLineEdit{\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"    border:2px solid #81BFDA;\n"
"    background-color: rgb(254, 254, 254)\n"
"\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color:rgb(220, 220, 220)\n"
"}")
        self.DetailsInput.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.DetailsInput.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.DetailsInput.setObjectName("DetailsInput")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.DetailsInput)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_9 = QtWidgets.QFrame(parent=self.DetailsInput)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_17.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_14 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_14.setStyleSheet("font: 87 12pt \"Montserrat Black\";")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_17.addWidget(self.label_14)
        self.gridLayout_4.addWidget(self.frame_9, 0, 0, 1, 1)
        self.FirstNameFrame = QtWidgets.QFrame(parent=self.DetailsInput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FirstNameFrame.sizePolicy().hasHeightForWidth())
        self.FirstNameFrame.setSizePolicy(sizePolicy)
        self.FirstNameFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FirstNameFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FirstNameFrame.setObjectName("FirstNameFrame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.FirstNameFrame)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_4 = QtWidgets.QLabel(parent=self.FirstNameFrame)
        self.label_4.setStyleSheet("font: 57  12pt \"Montserrat Medium\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_13.addWidget(self.label_4)
        self.FirstName = QtWidgets.QLineEdit(parent=self.FirstNameFrame)
        self.FirstName.setMinimumSize(QtCore.QSize(330, 49))
        self.FirstName.setStyleSheet("QLineEdit{\n"
"    font: 63 12pt \"Montserrat SemiBold\";\n"
"    color:rgb(25, 25, 25);\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"    border:2px solid #81BFDA;\n"
"    background-color: rgb(254, 254, 254);\n"
"\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color:rgb(230, 230, 230)\n"
"}")
        self.FirstName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.FirstName.setObjectName("FirstName")
        self.verticalLayout_13.addWidget(self.FirstName)
        self.gridLayout_4.addWidget(self.FirstNameFrame, 1, 0, 1, 1)
        self.LastNameFrame = QtWidgets.QFrame(parent=self.DetailsInput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LastNameFrame.sizePolicy().hasHeightForWidth())
        self.LastNameFrame.setSizePolicy(sizePolicy)
        self.LastNameFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.LastNameFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.LastNameFrame.setObjectName("LastNameFrame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.LastNameFrame)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_5 = QtWidgets.QLabel(parent=self.LastNameFrame)
        self.label_5.setStyleSheet("font: 57  12pt \"Montserrat Medium\";")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_14.addWidget(self.label_5)
        self.LastName = QtWidgets.QLineEdit(parent=self.LastNameFrame)
        self.LastName.setMinimumSize(QtCore.QSize(330, 49))
        self.LastName.setStyleSheet("QLineEdit{\n"
"    font: 63 12pt \"Montserrat SemiBold\";\n"
"    color:rgb(25, 25, 25);\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"    border:2px solid #81BFDA;\n"
"    background-color: rgb(254, 254, 254)\n"
"\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color:rgb(220, 220, 220)\n"
"}")
        self.LastName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LastName.setObjectName("LastName")
        self.verticalLayout_14.addWidget(self.LastName)
        self.gridLayout_4.addWidget(self.LastNameFrame, 1, 1, 1, 1)
        self.AddressFrame = QtWidgets.QFrame(parent=self.DetailsInput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddressFrame.sizePolicy().hasHeightForWidth())
        self.AddressFrame.setSizePolicy(sizePolicy)
        self.AddressFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.AddressFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.AddressFrame.setObjectName("AddressFrame")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.AddressFrame)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_6 = QtWidgets.QLabel(parent=self.AddressFrame)
        self.label_6.setStyleSheet("font: 57  12pt \"Montserrat Medium\";")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_15.addWidget(self.label_6)
        self.Address = QtWidgets.QLineEdit(parent=self.AddressFrame)
        self.Address.setMinimumSize(QtCore.QSize(330, 49))
        self.Address.setStyleSheet("QLineEdit{\n"
"    font: 63 12pt \"Montserrat SemiBold\";\n"
"    color:rgb(25, 25, 25);\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"    border:2px solid #81BFDA;\n"
"    background-color: rgb(254, 254, 254)\n"
"\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color:rgb(220, 220, 220)\n"
"}")
        self.Address.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Address.setObjectName("Address")
        self.verticalLayout_15.addWidget(self.Address)
        self.gridLayout_4.addWidget(self.AddressFrame, 2, 0, 1, 1)
        self.CellNoFrame = QtWidgets.QFrame(parent=self.DetailsInput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CellNoFrame.sizePolicy().hasHeightForWidth())
        self.CellNoFrame.setSizePolicy(sizePolicy)
        self.CellNoFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.CellNoFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.CellNoFrame.setObjectName("CellNoFrame")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.CellNoFrame)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_11 = QtWidgets.QLabel(parent=self.CellNoFrame)
        self.label_11.setStyleSheet("font: 57  12pt \"Montserrat Medium\";")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_16.addWidget(self.label_11)
        self.CellNo = QtWidgets.QLineEdit(parent=self.CellNoFrame)
        self.CellNo.setMinimumSize(QtCore.QSize(330, 49))
        self.CellNo.setStyleSheet("QLineEdit{\n"
"    font: 63 12pt \"Montserrat SemiBold\";\n"
"    color:rgb(25, 25, 25);\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"    border:2px solid #81BFDA;\n"
"    background-color: rgb(254, 254, 254)\n"
"\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color:rgb(220, 220, 220)\n"
"}")
        self.CellNo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.CellNo.setObjectName("CellNo")
        self.verticalLayout_16.addWidget(self.CellNo)
        self.gridLayout_4.addWidget(self.CellNoFrame, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(parent=self.DetailsInput)
        self.label_15.setStyleSheet("font: 87 12pt \"Montserrat Black\";")
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 3, 0, 1, 1)
        self.PetNameFrame = QtWidgets.QFrame(parent=self.DetailsInput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PetNameFrame.sizePolicy().hasHeightForWidth())
        self.PetNameFrame.setSizePolicy(sizePolicy)
        self.PetNameFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.PetNameFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.PetNameFrame.setObjectName("PetNameFrame")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.PetNameFrame)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_16 = QtWidgets.QLabel(parent=self.PetNameFrame)
        self.label_16.setStyleSheet("font: 57  12pt \"Montserrat Medium\";")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_18.addWidget(self.label_16)
        self.PetName = QtWidgets.QLineEdit(parent=self.PetNameFrame)
        self.PetName.setMinimumSize(QtCore.QSize(330, 49))
        self.PetName.setStyleSheet("QLineEdit{\n"
"    font: 63 12pt \"Montserrat SemiBold\";\n"
"    color:rgb(25, 25, 25);\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"    border:2px solid #81BFDA;\n"
"    background-color: rgb(254, 254, 254)\n"
"\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color:rgb(220, 220, 220)\n"
"}")
        self.PetName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.PetName.setObjectName("PetName")
        self.verticalLayout_18.addWidget(self.PetName)
        self.gridLayout_4.addWidget(self.PetNameFrame, 4, 0, 1, 1)
        self.ColorFrame = QtWidgets.QFrame(parent=self.DetailsInput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ColorFrame.sizePolicy().hasHeightForWidth())
        self.ColorFrame.setSizePolicy(sizePolicy)
        self.ColorFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ColorFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ColorFrame.setObjectName("ColorFrame")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.ColorFrame)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_17 = QtWidgets.QLabel(parent=self.ColorFrame)
        self.label_17.setStyleSheet("font: 57  12pt \"Montserrat Medium\";")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_19.addWidget(self.label_17)
        self.Color = QtWidgets.QLineEdit(parent=self.ColorFrame)
        self.Color.setMinimumSize(QtCore.QSize(330, 49))
        self.Color.setStyleSheet("QLineEdit{\n"
"    font: 63 12pt \"Montserrat SemiBold\";\n"
"    color:rgb(25, 25, 25);\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"    border:2px solid #81BFDA;\n"
"    background-color: rgb(254, 254, 254)\n"
"\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color:rgb(220, 220, 220)\n"
"}")
        self.Color.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Color.setObjectName("Color")
        self.verticalLayout_19.addWidget(self.Color)
        self.gridLayout_4.addWidget(self.ColorFrame, 4, 1, 1, 1)
        self.BreedFrame = QtWidgets.QFrame(parent=self.DetailsInput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BreedFrame.sizePolicy().hasHeightForWidth())
        self.BreedFrame.setSizePolicy(sizePolicy)
        self.BreedFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.BreedFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.BreedFrame.setObjectName("BreedFrame")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.BreedFrame)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_18 = QtWidgets.QLabel(parent=self.BreedFrame)
        self.label_18.setStyleSheet("font: 57  12pt \"Montserrat Medium\";")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_20.addWidget(self.label_18)
        self.Breed = QtWidgets.QLineEdit(parent=self.BreedFrame)
        self.Breed.setMinimumSize(QtCore.QSize(330, 49))
        self.Breed.setStyleSheet("QLineEdit{\n"
"    font: 63 12pt \"Montserrat SemiBold\";\n"
"    color:rgb(25, 25, 25);\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"    border:2px solid #81BFDA;\n"
"    background-color: rgb(254, 254, 254)\n"
"\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color:rgb(220, 220, 220)\n"
"}")
        self.Breed.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Breed.setObjectName("Breed")
        self.verticalLayout_20.addWidget(self.Breed)
        self.gridLayout_4.addWidget(self.BreedFrame, 5, 0, 1, 1)
        self.SpeciesFrame = QtWidgets.QFrame(parent=self.DetailsInput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpeciesFrame.sizePolicy().hasHeightForWidth())
        self.SpeciesFrame.setSizePolicy(sizePolicy)
        self.SpeciesFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.SpeciesFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.SpeciesFrame.setObjectName("SpeciesFrame")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.SpeciesFrame)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_19 = QtWidgets.QLabel(parent=self.SpeciesFrame)
        self.label_19.setStyleSheet("font: 57  12pt \"Montserrat Medium\";")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_21.addWidget(self.label_19)
        self.Species = QtWidgets.QLineEdit(parent=self.SpeciesFrame)
        self.Species.setMinimumSize(QtCore.QSize(330, 49))
        self.Species.setStyleSheet("QLineEdit{\n"
"    font: 63 12pt \"Montserrat SemiBold\";\n"
"    color:rgb(25, 25, 25);\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"    border:2px solid #81BFDA;\n"
"    background-color: rgb(254, 254, 254)\n"
"\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color:rgb(220, 220, 220)\n"
"}")
        self.Species.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Species.setObjectName("Species")
        self.verticalLayout_21.addWidget(self.Species)
        self.gridLayout_4.addWidget(self.SpeciesFrame, 5, 1, 1, 1)
        self.BirthDay = QtWidgets.QFrame(parent=self.DetailsInput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BirthDay.sizePolicy().hasHeightForWidth())
        self.BirthDay.setSizePolicy(sizePolicy)
        self.BirthDay.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.BirthDay.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.BirthDay.setObjectName("BirthDay")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.BirthDay)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_25 = QtWidgets.QLabel(parent=self.BirthDay)
        self.label_25.setStyleSheet("font: 57  12pt \"Montserrat Medium\";")
        self.label_25.setObjectName("label_25")
        self.verticalLayout_29.addWidget(self.label_25)
        self.Birthday = QtWidgets.QLineEdit(parent=self.BirthDay)
        self.Birthday.setMinimumSize(QtCore.QSize(330, 49))
        self.Birthday.setStyleSheet("QLineEdit{\n"
"    font: 63 12pt \"Montserrat SemiBold\";\n"
"    color:rgb(25, 25, 25);\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"    border:2px solid #81BFDA;\n"
"    background-color: rgb(254, 254, 254)\n"
"\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color:rgb(220, 220, 220)\n"
"}")
        self.Birthday.setObjectName("Birthday")
        self.verticalLayout_29.addWidget(self.Birthday)
        self.gridLayout_4.addWidget(self.BirthDay, 6, 0, 1, 1)
        self.Sex = QtWidgets.QFrame(parent=self.DetailsInput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sex.sizePolicy().hasHeightForWidth())
        self.Sex.setSizePolicy(sizePolicy)
        self.Sex.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Sex.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Sex.setObjectName("Sex")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.Sex)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_27 = QtWidgets.QLabel(parent=self.Sex)
        self.label_27.setStyleSheet("font: 57  12pt \"Montserrat Medium\";")
        self.label_27.setObjectName("label_27")
        self.verticalLayout_31.addWidget(self.label_27)
        self.sex = QtWidgets.QComboBox(parent=self.Sex)
        self.sex.setMinimumSize(QtCore.QSize(330, 49))
        self.sex.setAutoFillBackground(False)
        self.sex.setStyleSheet("QComboBox {\n"
"        background-color: #ffffff; \n"
"        border: 2px solid #81BFDA; \n"
"        border-radius: 15px;\n"
"        padding-left: 130;\n"
"        font: 63 12pt \"Montserrat SemiBold\";\n"
"        color:black;\n"
"    }\n"
"\n"
"QComboBox::item:selected { \n"
"    color: black;\n"
" }\n"
"QComboBox::item:!selected {\n"
"     color: gray; \n"
"}\n"
"QComboBox::drop-down {\n"
"        border: none;\n"
"        background: none;\n"
"        width: 30px;\n"
"    }\n"
"\n"
" QComboBox QAbstractItemView {\n"
"        background-color: white;\n"
"        border: 1px solid #81BFDA;\n"
"        border-radius:2px;\n"
"        selection-background-color: #3498db; \n"
"        selection-color: black;\n"
"        color: black;\n"
"        \n"
"    font: 63 8pt \"Montserrat SemiBold\";\n"
"    }\n"
"\n"
"")
        self.sex.setEditable(False)
        self.sex.setMaxVisibleItems(10)
        self.sex.setFrame(True)
        self.sex.setObjectName("sex")
        self.sex.addItem("")
        self.sex.addItem("")
        self.sex.addItem("")
        self.verticalLayout_31.addWidget(self.sex)
        self.gridLayout_4.addWidget(self.Sex, 6, 1, 1, 1)
        self.BreedFrame_5 = QtWidgets.QFrame(parent=self.DetailsInput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BreedFrame_5.sizePolicy().hasHeightForWidth())
        self.BreedFrame_5.setSizePolicy(sizePolicy)
        self.BreedFrame_5.setStyleSheet("QLineEdit{\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"    border:2px solid #81BFDA;\n"
"    background-color: rgb(254, 254, 254)\n"
"\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color:rgb(220, 220, 220)\n"
"}")
        self.BreedFrame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.BreedFrame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.BreedFrame_5.setObjectName("BreedFrame_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.BreedFrame_5)
        self.gridLayout_3.setContentsMargins(-1, 40, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.proceedBtn = QtWidgets.QToolButton(parent=self.BreedFrame_5)
        self.proceedBtn.setMinimumSize(QtCore.QSize(330, 0))
        self.proceedBtn.setMaximumSize(QtCore.QSize(16777215, 49))
        self.proceedBtn.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.proceedBtn.setStyleSheet("QToolButton{\n"
"    border:none;\n"
"    background-color:#78B3CE;\n"
"    font: 87 12pt \"Montserrat Black\";\n"
"    font-weight:bold;\n"
"    color:rgb(44, 44, 44);\n"
"    border-radius:15px;\n"
"    padding:10;\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Icons/right-arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.proceedBtn.setIcon(icon6)
        self.proceedBtn.setIconSize(QtCore.QSize(30, 30))
        self.proceedBtn.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.proceedBtn.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.proceedBtn.setObjectName("proceedBtn")
        self.gridLayout_3.addWidget(self.proceedBtn, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.BreedFrame_5, 7, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_27.addWidget(self.DetailsInput, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_9.addWidget(self.scrollArea)
        self.AddpatientStack.addWidget(self.InputPage)
        self.ConfirmationPage = QtWidgets.QWidget()
        self.ConfirmationPage.setObjectName("ConfirmationPage")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout(self.ConfirmationPage)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.ConfirmationPage)
        self.scrollArea_2.setStyleSheet("QScrollBar:vertical {\n"
"    border: none;\n"
"    background: white; \n"
"    width: 8px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #81BFDA; /* Scrollbar color */\n"
"    max-height: 15px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #2980b9; \n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical, \n"
"QScrollBar::sub-line:vertical, \n"
"QScrollBar::up-arrow:vertical, \n"
"QScrollBar::down-arrow:vertical, \n"
"QScrollBar::add-page:vertical, \n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"    height: 0px;\n"
"}")
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, -174, 849, 820))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_6)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.frame_5 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_6)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_5)
        self.frame_6.setMinimumSize(QtCore.QSize(735, 62))
        self.frame_6.setMaximumSize(QtCore.QSize(735, 62))
        self.frame_6.setStyleSheet("QFrame{\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color: #81BFDA;\n"
"\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_20 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_20.setStyleSheet("QLabel{\n"
"    color:black;\n"
"    font: 81 26pt \"Montserrat ExtraBold\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_2.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_21.setMinimumSize(QtCore.QSize(30, 30))
        self.label_21.setMaximumSize(QtCore.QSize(30, 30))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap(":/Icons/Icons/UserIcon.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_2.addWidget(self.label_21)
        self.verticalLayout_32.addWidget(self.frame_6)
        self.verticalLayout_30.addWidget(self.frame_5, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.DetailsInput_2 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_6)
        self.DetailsInput_2.setStyleSheet("QLabel{\n"
"    color:balack;\n"
"}\n"
"QLineEdit{\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"    border:2px solid #81BFDA;\n"
"    background-color: rgb(254, 254, 254)\n"
"\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color:rgb(220, 220, 220)\n"
"}")
        self.DetailsInput_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.DetailsInput_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.DetailsInput_2.setObjectName("DetailsInput_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.DetailsInput_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_10 = QtWidgets.QFrame(parent=self.DetailsInput_2)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_22.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_22 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_22.setStyleSheet("font: 87 12pt \"Montserrat Black\";")
        self.label_22.setObjectName("label_22")
        self.verticalLayout_22.addWidget(self.label_22)
        self.gridLayout_5.addWidget(self.frame_10, 0, 0, 1, 1)
        self.FirstNameFrame_2 = QtWidgets.QFrame(parent=self.DetailsInput_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FirstNameFrame_2.sizePolicy().hasHeightForWidth())
        self.FirstNameFrame_2.setSizePolicy(sizePolicy)
        self.FirstNameFrame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FirstNameFrame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FirstNameFrame_2.setObjectName("FirstNameFrame_2")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.FirstNameFrame_2)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_23 = QtWidgets.QLabel(parent=self.FirstNameFrame_2)
        self.label_23.setStyleSheet("font: 57  12pt \"Montserrat Medium\";")
        self.label_23.setObjectName("label_23")
        self.verticalLayout_23.addWidget(self.label_23)
        self.FirstNameConfirm = QtWidgets.QLineEdit(parent=self.FirstNameFrame_2)
        self.FirstNameConfirm.setMinimumSize(QtCore.QSize(330, 49))
        self.FirstNameConfirm.setStyleSheet("QLineEdit{\n"
"    font: 63 12pt \"Montserrat SemiBold\";\n"
"    color:rgb(25, 25, 25);\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"    border:2px solid #81BFDA;\n"
"    background-color: rgb(254, 254, 254);\n"
"\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color:rgb(230, 230, 230)\n"
"}")
        self.FirstNameConfirm.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.FirstNameConfirm.setObjectName("FirstNameConfirm")
        self.verticalLayout_23.addWidget(self.FirstNameConfirm)
        self.gridLayout_5.addWidget(self.FirstNameFrame_2, 1, 0, 1, 1)
        self.LastNameFrame_2 = QtWidgets.QFrame(parent=self.DetailsInput_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LastNameFrame_2.sizePolicy().hasHeightForWidth())
        self.LastNameFrame_2.setSizePolicy(sizePolicy)
        self.LastNameFrame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.LastNameFrame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.LastNameFrame_2.setObjectName("LastNameFrame_2")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.LastNameFrame_2)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_24 = QtWidgets.QLabel(parent=self.LastNameFrame_2)
        self.label_24.setStyleSheet("font: 57  12pt \"Montserrat Medium\";")
        self.label_24.setObjectName("label_24")
        self.verticalLayout_24.addWidget(self.label_24)
        self.LastNameConfirm = QtWidgets.QLineEdit(parent=self.LastNameFrame_2)
        self.LastNameConfirm.setMinimumSize(QtCore.QSize(330, 49))
        self.LastNameConfirm.setStyleSheet("QLineEdit{\n"
"    font: 63 12pt \"Montserrat SemiBold\";\n"
"    color:rgb(25, 25, 25);\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"    border:2px solid #81BFDA;\n"
"    background-color: rgb(254, 254, 254)\n"
"\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color:rgb(220, 220, 220)\n"
"}")
        self.LastNameConfirm.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LastNameConfirm.setObjectName("LastNameConfirm")
        self.verticalLayout_24.addWidget(self.LastNameConfirm)
        self.gridLayout_5.addWidget(self.LastNameFrame_2, 1, 1, 1, 1)
        self.AddressFrame_2 = QtWidgets.QFrame(parent=self.DetailsInput_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddressFrame_2.sizePolicy().hasHeightForWidth())
        self.AddressFrame_2.setSizePolicy(sizePolicy)
        self.AddressFrame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.AddressFrame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.AddressFrame_2.setObjectName("AddressFrame_2")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.AddressFrame_2)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_26 = QtWidgets.QLabel(parent=self.AddressFrame_2)
        self.label_26.setStyleSheet("font: 57  12pt \"Montserrat Medium\";")
        self.label_26.setObjectName("label_26")
        self.verticalLayout_25.addWidget(self.label_26)
        self.AddressConfirm = QtWidgets.QLineEdit(parent=self.AddressFrame_2)
        self.AddressConfirm.setMinimumSize(QtCore.QSize(330, 49))
        self.AddressConfirm.setStyleSheet("QLineEdit{\n"
"    font: 63 12pt \"Montserrat SemiBold\";\n"
"    color:rgb(25, 25, 25);\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"    border:2px solid #81BFDA;\n"
"    background-color: rgb(254, 254, 254)\n"
"\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color:rgb(220, 220, 220)\n"
"}")
        self.AddressConfirm.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.AddressConfirm.setObjectName("AddressConfirm")
        self.verticalLayout_25.addWidget(self.AddressConfirm)
        self.gridLayout_5.addWidget(self.AddressFrame_2, 2, 0, 1, 1)
        self.CellNoFrame_2 = QtWidgets.QFrame(parent=self.DetailsInput_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CellNoFrame_2.sizePolicy().hasHeightForWidth())
        self.CellNoFrame_2.setSizePolicy(sizePolicy)
        self.CellNoFrame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.CellNoFrame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.CellNoFrame_2.setObjectName("CellNoFrame_2")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.CellNoFrame_2)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_28 = QtWidgets.QLabel(parent=self.CellNoFrame_2)
        self.label_28.setStyleSheet("font: 57  12pt \"Montserrat Medium\";")
        self.label_28.setObjectName("label_28")
        self.verticalLayout_26.addWidget(self.label_28)
        self.CellNoConfirm = QtWidgets.QLineEdit(parent=self.CellNoFrame_2)
        self.CellNoConfirm.setMinimumSize(QtCore.QSize(330, 49))
        self.CellNoConfirm.setStyleSheet("QLineEdit{\n"
"    font: 63 12pt \"Montserrat SemiBold\";\n"
"    color:rgb(25, 25, 25);\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"    border:2px solid #81BFDA;\n"
"    background-color: rgb(254, 254, 254)\n"
"\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color:rgb(220, 220, 220)\n"
"}")
        self.CellNoConfirm.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.CellNoConfirm.setObjectName("CellNoConfirm")
        self.verticalLayout_26.addWidget(self.CellNoConfirm)
        self.gridLayout_5.addWidget(self.CellNoFrame_2, 2, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(parent=self.DetailsInput_2)
        self.label_29.setStyleSheet("font: 87 12pt \"Montserrat Black\";")
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 3, 0, 1, 1)
        self.PetNameFrame_2 = QtWidgets.QFrame(parent=self.DetailsInput_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PetNameFrame_2.sizePolicy().hasHeightForWidth())
        self.PetNameFrame_2.setSizePolicy(sizePolicy)
        self.PetNameFrame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.PetNameFrame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.PetNameFrame_2.setObjectName("PetNameFrame_2")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.PetNameFrame_2)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_30 = QtWidgets.QLabel(parent=self.PetNameFrame_2)
        self.label_30.setStyleSheet("font: 57  12pt \"Montserrat Medium\";")
        self.label_30.setObjectName("label_30")
        self.verticalLayout_33.addWidget(self.label_30)
        self.PetNameConfirm = QtWidgets.QLineEdit(parent=self.PetNameFrame_2)
        self.PetNameConfirm.setMinimumSize(QtCore.QSize(330, 49))
        self.PetNameConfirm.setStyleSheet("QLineEdit{\n"
"    font: 63 12pt \"Montserrat SemiBold\";\n"
"    color:rgb(25, 25, 25);\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"    border:2px solid #81BFDA;\n"
"    background-color: rgb(254, 254, 254)\n"
"\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color:rgb(220, 220, 220)\n"
"}")
        self.PetNameConfirm.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.PetNameConfirm.setObjectName("PetNameConfirm")
        self.verticalLayout_33.addWidget(self.PetNameConfirm)
        self.gridLayout_5.addWidget(self.PetNameFrame_2, 4, 0, 1, 1)
        self.ColorFrame_2 = QtWidgets.QFrame(parent=self.DetailsInput_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ColorFrame_2.sizePolicy().hasHeightForWidth())
        self.ColorFrame_2.setSizePolicy(sizePolicy)
        self.ColorFrame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ColorFrame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ColorFrame_2.setObjectName("ColorFrame_2")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.ColorFrame_2)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_31 = QtWidgets.QLabel(parent=self.ColorFrame_2)
        self.label_31.setStyleSheet("font: 57  12pt \"Montserrat Medium\";")
        self.label_31.setObjectName("label_31")
        self.verticalLayout_34.addWidget(self.label_31)
        self.ColorConfirm = QtWidgets.QLineEdit(parent=self.ColorFrame_2)
        self.ColorConfirm.setMinimumSize(QtCore.QSize(330, 49))
        self.ColorConfirm.setStyleSheet("QLineEdit{\n"
"    font: 63 12pt \"Montserrat SemiBold\";\n"
"    color:rgb(25, 25, 25);\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"    border:2px solid #81BFDA;\n"
"    background-color: rgb(254, 254, 254)\n"
"\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color:rgb(220, 220, 220)\n"
"}")
        self.ColorConfirm.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ColorConfirm.setObjectName("ColorConfirm")
        self.verticalLayout_34.addWidget(self.ColorConfirm)
        self.gridLayout_5.addWidget(self.ColorFrame_2, 4, 1, 1, 1)
        self.BreedFrame_3 = QtWidgets.QFrame(parent=self.DetailsInput_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BreedFrame_3.sizePolicy().hasHeightForWidth())
        self.BreedFrame_3.setSizePolicy(sizePolicy)
        self.BreedFrame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.BreedFrame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.BreedFrame_3.setObjectName("BreedFrame_3")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.BreedFrame_3)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_32 = QtWidgets.QLabel(parent=self.BreedFrame_3)
        self.label_32.setStyleSheet("font: 57  12pt \"Montserrat Medium\";")
        self.label_32.setObjectName("label_32")
        self.verticalLayout_35.addWidget(self.label_32)
        self.BreedConfirm = QtWidgets.QLineEdit(parent=self.BreedFrame_3)
        self.BreedConfirm.setMinimumSize(QtCore.QSize(330, 49))
        self.BreedConfirm.setStyleSheet("QLineEdit{\n"
"    font: 63 12pt \"Montserrat SemiBold\";\n"
"    color:rgb(25, 25, 25);\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"    border:2px solid #81BFDA;\n"
"    background-color: rgb(254, 254, 254)\n"
"\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color:rgb(220, 220, 220)\n"
"}")
        self.BreedConfirm.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.BreedConfirm.setObjectName("BreedConfirm")
        self.verticalLayout_35.addWidget(self.BreedConfirm)
        self.gridLayout_5.addWidget(self.BreedFrame_3, 5, 0, 1, 1)
        self.SpeciesFrame_2 = QtWidgets.QFrame(parent=self.DetailsInput_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpeciesFrame_2.sizePolicy().hasHeightForWidth())
        self.SpeciesFrame_2.setSizePolicy(sizePolicy)
        self.SpeciesFrame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.SpeciesFrame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.SpeciesFrame_2.setObjectName("SpeciesFrame_2")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.SpeciesFrame_2)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label_33 = QtWidgets.QLabel(parent=self.SpeciesFrame_2)
        self.label_33.setStyleSheet("font: 57  12pt \"Montserrat Medium\";")
        self.label_33.setObjectName("label_33")
        self.verticalLayout_36.addWidget(self.label_33)
        self.SpeciesConfirm = QtWidgets.QLineEdit(parent=self.SpeciesFrame_2)
        self.SpeciesConfirm.setMinimumSize(QtCore.QSize(330, 49))
        self.SpeciesConfirm.setStyleSheet("QLineEdit{\n"
"    font: 63 12pt \"Montserrat SemiBold\";\n"
"    color:rgb(25, 25, 25);\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"    border:2px solid #81BFDA;\n"
"    background-color: rgb(254, 254, 254)\n"
"\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color:rgb(220, 220, 220)\n"
"}")
        self.SpeciesConfirm.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.SpeciesConfirm.setObjectName("SpeciesConfirm")
        self.verticalLayout_36.addWidget(self.SpeciesConfirm)
        self.gridLayout_5.addWidget(self.SpeciesFrame_2, 5, 1, 1, 1)
        self.BirthDay_2 = QtWidgets.QFrame(parent=self.DetailsInput_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BirthDay_2.sizePolicy().hasHeightForWidth())
        self.BirthDay_2.setSizePolicy(sizePolicy)
        self.BirthDay_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.BirthDay_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.BirthDay_2.setObjectName("BirthDay_2")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.BirthDay_2)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.label_34 = QtWidgets.QLabel(parent=self.BirthDay_2)
        self.label_34.setStyleSheet("font: 57  12pt \"Montserrat Medium\";")
        self.label_34.setObjectName("label_34")
        self.verticalLayout_37.addWidget(self.label_34)
        self.BirthdayConfirm = QtWidgets.QLineEdit(parent=self.BirthDay_2)
        self.BirthdayConfirm.setMinimumSize(QtCore.QSize(330, 49))
        self.BirthdayConfirm.setStyleSheet("QLineEdit{\n"
"    font: 63 12pt \"Montserrat SemiBold\";\n"
"    color:rgb(25, 25, 25);\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"    border:2px solid #81BFDA;\n"
"    background-color: rgb(254, 254, 254)\n"
"\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color:rgb(220, 220, 220)\n"
"}")
        self.BirthdayConfirm.setObjectName("BirthdayConfirm")
        self.verticalLayout_37.addWidget(self.BirthdayConfirm)
        self.gridLayout_5.addWidget(self.BirthDay_2, 6, 0, 1, 1)
        self.BreedFrame_7 = QtWidgets.QFrame(parent=self.DetailsInput_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BreedFrame_7.sizePolicy().hasHeightForWidth())
        self.BreedFrame_7.setSizePolicy(sizePolicy)
        self.BreedFrame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.BreedFrame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.BreedFrame_7.setObjectName("BreedFrame_7")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.BreedFrame_7)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.label_35 = QtWidgets.QLabel(parent=self.BreedFrame_7)
        self.label_35.setStyleSheet("font: 57  12pt \"Montserrat Medium\";")
        self.label_35.setObjectName("label_35")
        self.verticalLayout_38.addWidget(self.label_35)
        self.sexConfirm = QtWidgets.QComboBox(parent=self.BreedFrame_7)
        self.sexConfirm.setMinimumSize(QtCore.QSize(330, 49))
        self.sexConfirm.setAutoFillBackground(False)
        self.sexConfirm.setStyleSheet("QComboBox {\n"
"        background-color: #ffffff; \n"
"        border: 2px solid #81BFDA; \n"
"        border-radius: 15px;\n"
"        padding-left: 130;\n"
"        font: 63 12pt \"Montserrat SemiBold\";\n"
"        color:black;\n"
"    }\n"
"\n"
"QComboBox::item:selected { \n"
"    color: black;\n"
" }\n"
"QComboBox::item:!selected {\n"
"     color: gray; \n"
"}\n"
"QComboBox::drop-down {\n"
"        border: none;\n"
"        background: none;\n"
"        width: 30px;\n"
"    }\n"
"\n"
" QComboBox QAbstractItemView {\n"
"        background-color: white;\n"
"        border: 1px solid #81BFDA;\n"
"        border-radius:2px;\n"
"        selection-background-color: #3498db; \n"
"        selection-color: black;\n"
"        color: black;\n"
"        \n"
"    font: 63 8pt \"Montserrat SemiBold\";\n"
"    }\n"
"\n"
"")
        self.sexConfirm.setEditable(False)
        self.sexConfirm.setMaxVisibleItems(10)
        self.sexConfirm.setFrame(True)
        self.sexConfirm.setObjectName("sexConfirm")
        self.sexConfirm.addItem("")
        self.sexConfirm.addItem("")
        self.sexConfirm.addItem("")
        self.verticalLayout_38.addWidget(self.sexConfirm)
        self.gridLayout_5.addWidget(self.BreedFrame_7, 6, 1, 1, 1)
        self.BreedFrame_8 = QtWidgets.QFrame(parent=self.DetailsInput_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BreedFrame_8.sizePolicy().hasHeightForWidth())
        self.BreedFrame_8.setSizePolicy(sizePolicy)
        self.BreedFrame_8.setStyleSheet("QLineEdit{\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"    border:2px solid #81BFDA;\n"
"    background-color: rgb(254, 254, 254)\n"
"\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color:rgb(220, 220, 220)\n"
"}")
        self.BreedFrame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.BreedFrame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.BreedFrame_8.setObjectName("BreedFrame_8")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.BreedFrame_8)
        self.gridLayout_6.setContentsMargins(-1, 40, -1, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.proceedBtn_2 = QtWidgets.QToolButton(parent=self.BreedFrame_8)
        self.proceedBtn_2.setMinimumSize(QtCore.QSize(330, 0))
        self.proceedBtn_2.setMaximumSize(QtCore.QSize(16777215, 49))
        self.proceedBtn_2.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.proceedBtn_2.setStyleSheet("QToolButton{\n"
"    border:none;\n"
"    background-color:#78B3CE;\n"
"    font: 87 12pt \"Montserrat Black\";\n"
"    font-weight:bold;\n"
"    color:rgb(44, 44, 44);\n"
"    border-radius:15px;\n"
"    padding:10;\n"
"}\n"
"")
        self.proceedBtn_2.setIcon(icon6)
        self.proceedBtn_2.setIconSize(QtCore.QSize(30, 30))
        self.proceedBtn_2.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.proceedBtn_2.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.proceedBtn_2.setObjectName("proceedBtn_2")
        self.gridLayout_6.addWidget(self.proceedBtn_2, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.BreedFrame_8, 7, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_30.addWidget(self.DetailsInput_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_6)
        self.verticalLayout_39.addWidget(self.scrollArea_2)
        self.AddpatientStack.addWidget(self.ConfirmationPage)
        self.verticalLayout_11.addWidget(self.AddpatientStack)
        self.verticalLayout_12.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.AddpatientPage)
        self.PetRecords = QtWidgets.QWidget()
        self.PetRecords.setObjectName("PetRecords")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.PetRecords)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_12 = QtWidgets.QLabel(parent=self.PetRecords)
        self.label_12.setStyleSheet("QLabel{\n"
"font: 81 36pt \"Montserrat ExtraBold\";\n"
"color:black;\n"
"}")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_10.addWidget(self.label_12)
        self.stackedWidget.addWidget(self.PetRecords)
        self.AppointmentPage = QtWidgets.QWidget()
        self.AppointmentPage.setObjectName("AppointmentPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.AppointmentPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_13 = QtWidgets.QLabel(parent=self.AppointmentPage)
        self.label_13.setStyleSheet("QLabel{\n"
"font: 81 36pt \"Montserrat ExtraBold\";\n"
"color:black;\n"
"}")
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.AppointmentPage)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_3.addWidget(self.MainContent)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.AddpatientStack.setCurrentIndex(0)
        self.sex.setCurrentIndex(0)
        self.sexConfirm.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PETMATE INFORMATION SYSTEM"))
        self.homeBtn.setText(_translate("MainWindow", "           HOME"))
        self.addPatientBtn.setText(_translate("MainWindow", "     ADD PATIENT"))
        self.petRecordsBtn.setText(_translate("MainWindow", "     PET RECORDS"))
        self.appointmentBtn.setText(_translate("MainWindow", "     APPOINTMENT"))
        self.label_7.setText(_translate("MainWindow", "Welcome to Petmate \n"
"Animal Clinic!\n"
""))
        self.label_8.setText(_translate("MainWindow", "Expert care, advanced treatments, \n"
"and a loving touch for your pets. \n"
"Keeping tails wagging and hearts happy!"))
        self.label_10.setText(_translate("MainWindow", "APPOINTMENT TODAY - DATE"))
        self.upcoming_appointment.setSortingEnabled(False)
        item = self.upcoming_appointment.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NAME"))
        item = self.upcoming_appointment.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CELL NO."))
        item = self.upcoming_appointment.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "PET\'S ID"))
        item = self.upcoming_appointment.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "TIME"))
        item = self.upcoming_appointment.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "SERVICE"))
        self.label_3.setText(_translate("MainWindow", "WELCOME, USER"))
        self.label_14.setText(_translate("MainWindow", "BASIC INFORMATION"))
        self.label_4.setText(_translate("MainWindow", "First Name"))
        self.label_5.setText(_translate("MainWindow", "Last Name"))
        self.label_6.setText(_translate("MainWindow", "Address"))
        self.label_11.setText(_translate("MainWindow", "Cell  No."))
        self.label_15.setText(_translate("MainWindow", "PET DETAILS"))
        self.label_16.setText(_translate("MainWindow", "Pet Name"))
        self.label_17.setText(_translate("MainWindow", "Color"))
        self.label_18.setText(_translate("MainWindow", "Breed"))
        self.label_19.setText(_translate("MainWindow", "Species"))
        self.label_25.setText(_translate("MainWindow", "Birthday"))
        self.label_27.setText(_translate("MainWindow", "Sex"))
        self.sex.setCurrentText(_translate("MainWindow", "Select Sex"))
        self.sex.setItemText(0, _translate("MainWindow", "Select Sex"))
        self.sex.setItemText(1, _translate("MainWindow", "Male"))
        self.sex.setItemText(2, _translate("MainWindow", "Female"))
        self.proceedBtn.setText(_translate("MainWindow", "                       PROCEED"))
        self.label_20.setText(_translate("MainWindow", "CONFIRMATION"))
        self.label_22.setText(_translate("MainWindow", "BASIC INFORMATION"))
        self.label_23.setText(_translate("MainWindow", "First Name"))
        self.label_24.setText(_translate("MainWindow", "Last Name"))
        self.label_26.setText(_translate("MainWindow", "Address"))
        self.label_28.setText(_translate("MainWindow", "Cell  No."))
        self.label_29.setText(_translate("MainWindow", "PET DETAILS"))
        self.label_30.setText(_translate("MainWindow", "Pet Name"))
        self.label_31.setText(_translate("MainWindow", "Color"))
        self.label_32.setText(_translate("MainWindow", "Breed"))
        self.label_33.setText(_translate("MainWindow", "Species"))
        self.label_34.setText(_translate("MainWindow", "Birthday"))
        self.label_35.setText(_translate("MainWindow", "Sex"))
        self.sexConfirm.setCurrentText(_translate("MainWindow", "Select Sex"))
        self.sexConfirm.setItemText(0, _translate("MainWindow", "Select Sex"))
        self.sexConfirm.setItemText(1, _translate("MainWindow", "Male"))
        self.sexConfirm.setItemText(2, _translate("MainWindow", "Female"))
        self.proceedBtn_2.setText(_translate("MainWindow", "                       PROCEED"))
        self.label_12.setText(_translate("MainWindow", "Pet Records Page"))
        self.label_13.setText(_translate("MainWindow", "APPOINT MENT PAGE"))
