# Form implementation generated from reading ui file 'Home.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/desktopIcon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    border:none;\n"
"\n"
"}")
        MainWindow.setIconSize(QtCore.QSize(31, 24))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    background-color: qlineargradient(\n"
"         y1: 0, x1: 0, y2: 1, x2: 0,\n"
"         stop: 0 #78B3CE, \n"
"         stop: 1 #D5EDF8\n"
"    );\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setContentsMargins(15, 15, 15, 15)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sideNav = QtWidgets.QFrame(parent=self.centralwidget)
        self.sideNav.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sideNav.sizePolicy().hasHeightForWidth())
        self.sideNav.setSizePolicy(sizePolicy)
        self.sideNav.setMinimumSize(QtCore.QSize(320, 694))
        self.sideNav.setStyleSheet("#sideNav{\n"
"    background-color:white;\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"}")
        self.sideNav.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.sideNav.setObjectName("sideNav")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sideNav)
        self.verticalLayout_2.setContentsMargins(-1, 29, -1, 40)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PetmateLogo = QtWidgets.QLabel(parent=self.sideNav)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PetmateLogo.sizePolicy().hasHeightForWidth())
        self.PetmateLogo.setSizePolicy(sizePolicy)
        self.PetmateLogo.setMinimumSize(QtCore.QSize(212, 81))
        self.PetmateLogo.setMaximumSize(QtCore.QSize(212, 81))
        self.PetmateLogo.setText("")
        self.PetmateLogo.setPixmap(QtGui.QPixmap(":/Images/image/petmateLogo.png"))
        self.PetmateLogo.setScaledContents(True)
        self.PetmateLogo.setObjectName("PetmateLogo")
        self.verticalLayout_2.addWidget(self.PetmateLogo, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.Buttons = QtWidgets.QFrame(parent=self.sideNav)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Buttons.sizePolicy().hasHeightForWidth())
        self.Buttons.setSizePolicy(sizePolicy)
        self.Buttons.setMinimumSize(QtCore.QSize(260, 260))
        self.Buttons.setMaximumSize(QtCore.QSize(260, 260))
        self.Buttons.setStyleSheet("QFrame{\n"
"    background-color:transparent;\n"
"}")
        self.Buttons.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.Buttons.setObjectName("Buttons")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Buttons)
        self.verticalLayout.setObjectName("verticalLayout")
        self.homeBtn = QtWidgets.QToolButton(parent=self.Buttons)
        self.homeBtn.setMinimumSize(QtCore.QSize(240, 0))
        self.homeBtn.setAutoFillBackground(False)
        self.homeBtn.setStyleSheet("QToolButton{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    font: 87 12pt \"Montserrat Black\";\n"
"    font-weight:bold;\n"
"    color:#78B3CE;\n"
"    border-radius:15px;\n"
"    padding:10;\n"
"}\n"
"QToolButton:hover{\n"
"    background-color: rgb(255, 241, 206);\n"
"\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.homeBtn.setIcon(icon1)
        self.homeBtn.setIconSize(QtCore.QSize(25, 25))
        self.homeBtn.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.homeBtn.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.homeBtn.setAutoRaise(False)
        self.homeBtn.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.homeBtn.setObjectName("homeBtn")
        self.verticalLayout.addWidget(self.homeBtn)
        self.addPatientBtn = QtWidgets.QToolButton(parent=self.Buttons)
        self.addPatientBtn.setMinimumSize(QtCore.QSize(240, 0))
        self.addPatientBtn.setAutoFillBackground(False)
        self.addPatientBtn.setStyleSheet("QToolButton{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    font: 87 12pt \"Montserrat Black\";\n"
"    font-weight:bold;\n"
"    color:#78B3CE;\n"
"    border-radius:15px;\n"
"    padding:10;\n"
"}\n"
"QToolButton:hover{\n"
"    background-color: rgb(255, 241, 206);\n"
"\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/AddIcon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.addPatientBtn.setIcon(icon2)
        self.addPatientBtn.setIconSize(QtCore.QSize(25, 25))
        self.addPatientBtn.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.addPatientBtn.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.addPatientBtn.setAutoRaise(False)
        self.addPatientBtn.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.addPatientBtn.setObjectName("addPatientBtn")
        self.verticalLayout.addWidget(self.addPatientBtn)
        self.petRecordsBtn = QtWidgets.QToolButton(parent=self.Buttons)
        self.petRecordsBtn.setMinimumSize(QtCore.QSize(240, 0))
        self.petRecordsBtn.setAutoFillBackground(False)
        self.petRecordsBtn.setStyleSheet("QToolButton{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    font: 87 12pt \"Montserrat Black\";\n"
"    font-weight:bold;\n"
"    color:#78B3CE;\n"
"    border-radius:15px;\n"
"    padding:10;\n"
"}\n"
"QToolButton:hover{\n"
"    background-color: rgb(255, 241, 206);\n"
"\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/petDetailsIcon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.petRecordsBtn.setIcon(icon3)
        self.petRecordsBtn.setIconSize(QtCore.QSize(25, 25))
        self.petRecordsBtn.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.petRecordsBtn.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.petRecordsBtn.setAutoRaise(False)
        self.petRecordsBtn.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.petRecordsBtn.setObjectName("petRecordsBtn")
        self.verticalLayout.addWidget(self.petRecordsBtn)
        self.appointmentBtn = QtWidgets.QToolButton(parent=self.Buttons)
        self.appointmentBtn.setMinimumSize(QtCore.QSize(240, 0))
        self.appointmentBtn.setAutoFillBackground(False)
        self.appointmentBtn.setStyleSheet("QToolButton{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    font: 87 12pt \"Montserrat Black\";\n"
"    font-weight:bold;\n"
"    color:#78B3CE;\n"
"    border-radius:15px;\n"
"    padding:10;\n"
"}\n"
"QToolButton:hover{\n"
"    background-color: rgb(255, 241, 206);\n"
"\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Icons/AppointmentIcon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.appointmentBtn.setIcon(icon4)
        self.appointmentBtn.setIconSize(QtCore.QSize(25, 25))
        self.appointmentBtn.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.appointmentBtn.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.appointmentBtn.setAutoRaise(False)
        self.appointmentBtn.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.appointmentBtn.setObjectName("appointmentBtn")
        self.verticalLayout.addWidget(self.appointmentBtn)
        self.schedVax = QtWidgets.QToolButton(parent=self.Buttons)
        self.schedVax.setMinimumSize(QtCore.QSize(240, 0))
        self.schedVax.setAutoFillBackground(False)
        self.schedVax.setStyleSheet("QToolButton{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    font: 87 11pt \"Montserrat Black\";\n"
"    font-weight:bold;\n"
"    color:#78B3CE;\n"
"    border-radius:15px;\n"
"    padding:10;\n"
"}\n"
"QToolButton:hover{\n"
"    background-color: rgb(255, 241, 206);\n"
"\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Icons/schedVax.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.schedVax.setIcon(icon5)
        self.schedVax.setIconSize(QtCore.QSize(25, 25))
        self.schedVax.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.schedVax.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.schedVax.setAutoRaise(False)
        self.schedVax.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.schedVax.setObjectName("schedVax")
        self.verticalLayout.addWidget(self.schedVax)
        self.verticalLayout_2.addWidget(self.Buttons, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=self.sideNav)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(220, 220))
        self.label.setMaximumSize(QtCore.QSize(220, 220))
        self.label.setStyleSheet("QLabel{\n"
"    margin-bottom:47pc;\n"
"\n"
"}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Images/image/navImg.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.toolButton = QtWidgets.QToolButton(parent=self.sideNav)
        self.toolButton.setMinimumSize(QtCore.QSize(240, 0))
        self.toolButton.setStyleSheet("QToolButton{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    font: 87 12pt \"Montserrat Black\";\n"
"    font-weight:bold;\n"
"    color:#78B3CE;\n"
"    border-radius:15px;\n"
"    padding:10;\n"
"}\n"
"QToolButton:hover{\n"
"    background-color: rgb(255, 241, 206);\n"
"\n"
"}")
        self.toolButton.setText("       LOG OUT")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Icons/logOutIcon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton.setIcon(icon6)
        self.toolButton.setIconSize(QtCore.QSize(30, 30))
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.toolButton.setObjectName("toolButton")
        self.verticalLayout_2.addWidget(self.toolButton, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.horizontalLayout_3.addWidget(self.sideNav)
        self.MainContent = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainContent.sizePolicy().hasHeightForWidth())
        self.MainContent.setSizePolicy(sizePolicy)
        self.MainContent.setStyleSheet("#MainContent{\n"
"    background-color:white;\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"}")
        self.MainContent.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.MainContent.setObjectName("MainContent")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.MainContent)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.MainContent)
        self.stackedWidget.setStyleSheet("QStackedWidget{\n"
"    background:transparent;\n"
"\n"
"}")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.homepage = QtWidgets.QWidget()
        self.homepage.setStyleSheet("QWidget{\n"
"    background:transparent;\n"
"\n"
"}")
        self.homepage.setObjectName("homepage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.homepage)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.home = QtWidgets.QFrame(parent=self.homepage)
        self.home.setStyleSheet("QFrame{\n"
"    background:transparent;\n"
"\n"
"}")
        self.home.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.home.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.home.setObjectName("home")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.home)
        self.verticalLayout_8.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame = QtWidgets.QFrame(parent=self.home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 250))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame.setStyleSheet("QFrame{\n"
"    background:transparent;\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setObjectName("frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_7.setContentsMargins(45, -1, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.welcome = QtWidgets.QFrame(parent=self.frame)
        self.welcome.setStyleSheet("QFrame{\n"
"    background:transparent;\n"
"\n"
"}")
        self.welcome.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.welcome.setObjectName("welcome")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.welcome)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(parent=self.welcome)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_7.setStyleSheet("QLabel{\n"
"    font: 81 32pt \"Montserrat ExtraBold\";\n"
"    color: #272727;\n"
"    text-align:left;\n"
"}\n"
"")
        self.label_7.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_8 = QtWidgets.QLabel(parent=self.welcome)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 80))
        self.label_8.setStyleSheet("QLabel{\n"
"    \n"
"    font: 25 14pt \"Montserrat Light\";\n"
"    color: #2A2A2A;\n"
"}\n"
"\n"
"")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.horizontalLayout_7.addWidget(self.welcome, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.picture = QtWidgets.QFrame(parent=self.frame)
        self.picture.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.picture.setObjectName("picture")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.picture)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(parent=self.picture)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(285, 285))
        self.label_9.setMaximumSize(QtCore.QSize(285, 285))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/Images/image/image 1.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.horizontalLayout_7.addWidget(self.picture)
        self.verticalLayout_8.addWidget(self.frame)
        self.Appointment = QtWidgets.QFrame(parent=self.home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Appointment.sizePolicy().hasHeightForWidth())
        self.Appointment.setSizePolicy(sizePolicy)
        self.Appointment.setMinimumSize(QtCore.QSize(0, 0))
        self.Appointment.setStyleSheet("QFrame{\n"
"    background:transparent;\n"
"\n"
"}")
        self.Appointment.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.Appointment.setObjectName("Appointment")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Appointment)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.appointment_date = QtWidgets.QFrame(parent=self.Appointment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appointment_date.sizePolicy().hasHeightForWidth())
        self.appointment_date.setSizePolicy(sizePolicy)
        self.appointment_date.setMinimumSize(QtCore.QSize(735, 62))
        self.appointment_date.setMaximumSize(QtCore.QSize(735, 62))
        self.appointment_date.setStyleSheet("QFrame{\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color: #81BFDA;\n"
"\n"
"}")
        self.appointment_date.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.appointment_date.setObjectName("appointment_date")
        self.gridLayout = QtWidgets.QGridLayout(self.appointment_date)
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtWidgets.QLabel(parent=self.appointment_date)
        self.label_10.setStyleSheet("QLabel{\n"
"    color:black;\n"
"    font: 81 26pt \"Montserrat ExtraBold\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_6.addWidget(self.appointment_date, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_8.addWidget(self.Appointment)
        self.verticalLayout_7.addWidget(self.home)
        self.stackedWidget.addWidget(self.homepage)
        self.AddpatientPage = QtWidgets.QWidget()
        self.AddpatientPage.setStyleSheet("QWidget{\n"
"    background:transparent;\n"
"\n"
"}")
        self.AddpatientPage.setObjectName("AddpatientPage")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.AddpatientPage)
        self.verticalLayout_12.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_2 = QtWidgets.QFrame(parent=self.AddpatientPage)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(50, 30, -1, 0)
        self.horizontalLayout.setSpacing(70)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setStyleSheet("font: 25pt \"Rubik Mono One\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setMaximumSize(QtCore.QSize(140, 60))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/Images/image/petmateLogo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout_12.addWidget(self.frame_2, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_3 = QtWidgets.QFrame(parent=self.AddpatientPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_9.setContentsMargins(50, 0, -1, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet("font: 16pt \"Rubik Mono One\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.ownerDetails = QtWidgets.QFrame(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ownerDetails.sizePolicy().hasHeightForWidth())
        self.ownerDetails.setSizePolicy(sizePolicy)
        self.ownerDetails.setStyleSheet("")
        self.ownerDetails.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ownerDetails.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ownerDetails.setObjectName("ownerDetails")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ownerDetails)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(parent=self.ownerDetails)
        self.label_6.setStyleSheet("font: 57 12pt \"Montserrat Medium\";")
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(parent=self.ownerDetails)
        self.label_14.setStyleSheet("font: 57 12pt \"Montserrat Medium\";")
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.ownerDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(174, 45))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    border-right: 2px solid #cccccc;\n"
"    border-bottom: 2px solid #cccccc;\n"
"    border-radius: 5px;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.ownerDetails)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(174, 45))
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"    border-right: 2px solid #cccccc;\n"
"    border-bottom: 2px solid #cccccc;\n"
"    border-radius: 5px;\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 1, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.ownerDetails)
        self.lineEdit.setMinimumSize(QtCore.QSize(174, 45))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border-right: 2px solid #cccccc;\n"
"    border-bottom: 2px solid #cccccc;\n"
"    border-radius: 5px;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=self.ownerDetails)
        self.label_11.setStyleSheet("font: 57 12pt \"Montserrat Medium\";")
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 8)
        self.gridLayout_3.setColumnStretch(1, 8)
        self.gridLayout_3.setColumnStretch(2, 8)
        self.verticalLayout_9.addWidget(self.ownerDetails)
        self.label_15 = QtWidgets.QLabel(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setStyleSheet("font: 16pt \"Rubik Mono One\";")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_9.addWidget(self.label_15)
        self.ownerDetails_2 = QtWidgets.QFrame(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ownerDetails_2.sizePolicy().hasHeightForWidth())
        self.ownerDetails_2.setSizePolicy(sizePolicy)
        self.ownerDetails_2.setStyleSheet("")
        self.ownerDetails_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ownerDetails_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ownerDetails_2.setObjectName("ownerDetails_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.ownerDetails_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_17 = QtWidgets.QLabel(parent=self.ownerDetails_2)
        self.label_17.setStyleSheet("font: 57 12pt \"Montserrat Medium\";")
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 1, 3, 1, 1)
        self.comboBox = QtWidgets.QComboBox(parent=self.ownerDetails_2)
        self.comboBox.setMinimumSize(QtCore.QSize(174, 45))
        self.comboBox.setStyleSheet("QComboBox{\n"
"    border-right: 2px solid #cccccc;\n"
"    border-bottom: 2px solid #cccccc;\n"
"    border-radius: 5px;\n"
"\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background-color:white;\n"
"    border: none;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/Icons/Icons/downArrow.png);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    padding-right: 10px;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_4.addWidget(self.comboBox, 2, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(parent=self.ownerDetails_2)
        self.label_18.setStyleSheet("font: 57 12pt \"Montserrat Medium\";")
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 1, 2, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.ownerDetails_2)
        self.comboBox_2.setMinimumSize(QtCore.QSize(174, 45))
        self.comboBox_2.setStyleSheet("QComboBox{\n"
"    border-right: 2px solid #cccccc;\n"
"    border-bottom: 2px solid #cccccc;\n"
"    border-radius: 5px;\n"
"    font: 63 11pt \"Montserrat SemiBold\";\n"
"    padding-left:5px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background-color:white;\n"
"    border: none;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/Icons/Icons/downArrow.png);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    selection-background-color: rgb(193, 193, 193); \n"
"    selection-color: black;\n"
"    font: 63 11pt \"Montserrat SemiBold\";    \n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    background-color: white;\n"
"    color: black;\n"
"    height: 25px;\n"
"    font: 63 11pt \"Montserrat SemiBold\";    \n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color:  rgb(193, 193, 193); \n"
"    color: black;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView QScrollBar {\n"
"    background-color: #f0f0f0; \n"
"    width: 10px; \n"
"}\n"
"QComboBox QAbstractItemView QScrollBar::handle {\n"
"    background-color: rgb(129, 191, 218); \n"
"    border-radius: 5px; \n"
"    min-height: 30px; \n"
"}\n"
"QComboBox QAbstractItemView QScrollBar::handle:hover {\n"
"    background-color: rgb(86, 127, 145)\n"
"}\n"
"QComboBox QAbstractItemView QScrollBar::add-line,\n"
"QComboBox QAbstractItemView QScrollBar::sub-line {\n"
"    background: none;\n"
"}")
        self.comboBox_2.setMaxVisibleItems(10)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_2, 2, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(parent=self.ownerDetails_2)
        self.label_16.setStyleSheet("font: 57 12pt \"Montserrat Medium\";")
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 1, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(parent=self.ownerDetails_2)
        self.comboBox_3.setMinimumSize(QtCore.QSize(174, 45))
        self.comboBox_3.setStyleSheet("QComboBox{\n"
"    border-right: 2px solid #cccccc;\n"
"    border-bottom: 2px solid #cccccc;\n"
"    border-radius: 5px;\n"
"\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background-color:white;\n"
"    border: none;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/Icons/Icons/downArrow.png);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    padding-right: 10px;\n"
"}")
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_4.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.ownerDetails_2)
        self.ownerDetails_3 = QtWidgets.QFrame(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ownerDetails_3.sizePolicy().hasHeightForWidth())
        self.ownerDetails_3.setSizePolicy(sizePolicy)
        self.ownerDetails_3.setStyleSheet("")
        self.ownerDetails_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ownerDetails_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ownerDetails_3.setObjectName("ownerDetails_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.ownerDetails_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_20 = QtWidgets.QLabel(parent=self.ownerDetails_3)
        self.label_20.setStyleSheet("font: 57 12pt \"Montserrat Medium\";")
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 0, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(parent=self.ownerDetails_3)
        self.label_21.setStyleSheet("font: 57 12pt \"Montserrat Medium\";")
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 0, 1, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(parent=self.ownerDetails_3)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(174, 45))
        self.lineEdit_8.setStyleSheet("QLineEdit{\n"
"    border-right: 2px solid #cccccc;\n"
"    border-bottom: 2px solid #cccccc;\n"
"    border-radius: 5px;\n"
"}")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_5.addWidget(self.lineEdit_8, 1, 2, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(parent=self.ownerDetails_3)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(174, 45))
        self.lineEdit_9.setStyleSheet("QLineEdit{\n"
"    border-right: 2px solid #cccccc;\n"
"    border-bottom: 2px solid #cccccc;\n"
"    border-radius: 5px;\n"
"}")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_5.addWidget(self.lineEdit_9, 1, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=self.ownerDetails_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(174, 45))
        self.lineEdit_7.setStyleSheet("QLineEdit{\n"
"    border-right: 2px solid #cccccc;\n"
"    border-bottom: 2px solid #cccccc;\n"
"    border-radius: 5px;\n"
"}")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_5.addWidget(self.lineEdit_7, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(parent=self.ownerDetails_3)
        self.label_19.setStyleSheet("font: 57 12pt \"Montserrat Medium\";")
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 0, 0, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 8)
        self.gridLayout_5.setColumnStretch(1, 8)
        self.gridLayout_5.setColumnStretch(2, 8)
        self.verticalLayout_9.addWidget(self.ownerDetails_3)
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton.setMinimumSize(QtCore.QSize(174, 45))
        self.pushButton.setMaximumSize(QtCore.QSize(174, 16777215))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    font: 63 15pt \"Montserrat SemiBold\";\n"
"    background-color:rgb(129, 191, 218);\n"
"    border-radius: 5px;\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(110, 163, 186);\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_9.addWidget(self.pushButton, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_12.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.AddpatientPage)
        self.PetRecords = QtWidgets.QWidget()
        self.PetRecords.setObjectName("PetRecords")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.PetRecords)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_12 = QtWidgets.QLabel(parent=self.PetRecords)
        self.label_12.setStyleSheet("QLabel{\n"
"font: 81 36pt \"Montserrat ExtraBold\";\n"
"color:black;\n"
"}")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_10.addWidget(self.label_12)
        self.stackedWidget.addWidget(self.PetRecords)
        self.AppointmentPage = QtWidgets.QWidget()
        self.AppointmentPage.setObjectName("AppointmentPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.AppointmentPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_13 = QtWidgets.QLabel(parent=self.AppointmentPage)
        self.label_13.setStyleSheet("QLabel{\n"
"font: 81 36pt \"Montserrat ExtraBold\";\n"
"color:black;\n"
"}")
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.AppointmentPage)
        self.SchedVax = QtWidgets.QWidget()
        self.SchedVax.setObjectName("SchedVax")
        self.label_5 = QtWidgets.QLabel(parent=self.SchedVax)
        self.label_5.setGeometry(QtCore.QRect(210, 220, 47, 13))
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.SchedVax)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_3.addWidget(self.MainContent)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PETMATE INFORMATION SYSTEM"))
        self.homeBtn.setText(_translate("MainWindow", "HOME"))
        self.addPatientBtn.setText(_translate("MainWindow", "ADD PATIENT"))
        self.petRecordsBtn.setText(_translate("MainWindow", "PET RECORDS"))
        self.appointmentBtn.setText(_translate("MainWindow", "APPOINTMENT"))
        self.schedVax.setText(_translate("MainWindow", "SCHEDULED VACCINES"))
        self.label_7.setText(_translate("MainWindow", "Welcome to Petmate \n"
"Animal Clinic!\n"
""))
        self.label_8.setText(_translate("MainWindow", "Expert care, advanced treatments, \n"
"and a loving touch for your pets. \n"
"Keeping tails wagging and hearts happy!"))
        self.label_10.setText(_translate("MainWindow", "APPOINTMENT TODAY - DATE"))
        self.label_2.setText(_translate("MainWindow", "PETMATE ANIMAL CLINIC"))
        self.label_4.setText(_translate("MainWindow", "BASIC INFORMATION"))
        self.label_6.setText(_translate("MainWindow", "First name"))
        self.label_14.setText(_translate("MainWindow", "Phone number"))
        self.label_11.setText(_translate("MainWindow", "Last name"))
        self.label_15.setText(_translate("MainWindow", "ADDRESS"))
        self.label_17.setText(_translate("MainWindow", "Barangay"))
        self.label_18.setText(_translate("MainWindow", "City/Municipality"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Imus City ★"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Alfonso"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Amadeo"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Bacoor City"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Carmona"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "Cavite City"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "Dasmariñas City"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "General Emilio Aguinaldo"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "General Mariano Alvarez"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "General Trias City"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "Indang"))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "Kawit"))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "Magallanes"))
        self.comboBox_2.setItemText(13, _translate("MainWindow", "Maragondon"))
        self.comboBox_2.setItemText(14, _translate("MainWindow", "Mendez"))
        self.comboBox_2.setItemText(15, _translate("MainWindow", "Naic"))
        self.comboBox_2.setItemText(16, _translate("MainWindow", "Noveleta"))
        self.comboBox_2.setItemText(17, _translate("MainWindow", "Rosario"))
        self.comboBox_2.setItemText(18, _translate("MainWindow", "Silang"))
        self.comboBox_2.setItemText(19, _translate("MainWindow", "Tagaytay City"))
        self.comboBox_2.setItemText(20, _translate("MainWindow", "Tanza"))
        self.comboBox_2.setItemText(21, _translate("MainWindow", "Ternate"))
        self.comboBox_2.setItemText(22, _translate("MainWindow", "Trece Martires City"))
        self.label_16.setText(_translate("MainWindow", "Province"))
        self.label_20.setText(_translate("MainWindow", "Emergency no."))
        self.label_21.setText(_translate("MainWindow", "Email"))
        self.label_19.setText(_translate("MainWindow", "Subdivision/Ph/Blk-L"))
        self.pushButton.setText(_translate("MainWindow", "CONFIRM"))
        self.label_12.setText(_translate("MainWindow", "Pet Records Page"))
        self.label_13.setText(_translate("MainWindow", "APPOINTMENT PAGE"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
