# Form implementation generated from reading ui file 'Home.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 726)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/desktopIcon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    border:none;\n"
"\n"
"}")
        MainWindow.setIconSize(QtCore.QSize(31, 24))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    background-color: qlineargradient(\n"
"         y1: 0, x1: 0, y2: 1, x2: 0,\n"
"         stop: 0 #78B3CE, \n"
"         stop: 1 #D5EDF8\n"
"    );\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.MainContent = QtWidgets.QFrame(parent=self.centralwidget)
        self.MainContent.setStyleSheet("#MainContent{\n"
"    background-color:white;\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"}")
        self.MainContent.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.MainContent.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.MainContent.setObjectName("MainContent")
        self.gridLayout_3.addWidget(self.MainContent, 0, 2, 1, 1)
        self.sideNav = QtWidgets.QFrame(parent=self.centralwidget)
        self.sideNav.setMaximumSize(QtCore.QSize(321, 694))
        self.sideNav.setStyleSheet("#sideNav{\n"
"    background-color:white;\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"}")
        self.sideNav.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.sideNav.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.sideNav.setObjectName("sideNav")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.sideNav)
        self.gridLayout_2.setContentsMargins(30, 0, 0, 40)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(parent=self.sideNav)
        self.label.setMinimumSize(QtCore.QSize(220, 220))
        self.label.setMaximumSize(QtCore.QSize(220, 220))
        self.label.setStyleSheet("QLabel{\n"
"    margin-bottom:47pc;\n"
"\n"
"}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Images/image/navImg.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 5, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 29, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.logoutBtn = QtWidgets.QFrame(parent=self.sideNav)
        self.logoutBtn.setMinimumSize(QtCore.QSize(240, 42))
        self.logoutBtn.setMaximumSize(QtCore.QSize(240, 42))
        self.logoutBtn.setStyleSheet("QFrame{\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background-color: #FCD597;\n"
"}")
        self.logoutBtn.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.logoutBtn.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.logoutBtn.setObjectName("logoutBtn")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.logoutBtn)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(parent=self.logoutBtn)
        self.label_6.setMinimumSize(QtCore.QSize(30, 30))
        self.label_6.setMaximumSize(QtCore.QSize(30, 30))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/Icons/Icons/logOutIcon.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.logoutBtn)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    font-size:14px;\n"
"    font-weight:bold;\n"
"    color:#78B3CE;\n"
"    \n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.gridLayout_2.addWidget(self.logoutBtn, 8, 0, 1, 1)
        self.Buttons = QtWidgets.QFrame(parent=self.sideNav)
        self.Buttons.setMinimumSize(QtCore.QSize(240, 0))
        self.Buttons.setMaximumSize(QtCore.QSize(240, 250))
        self.Buttons.setStyleSheet("QFrame{\n"
"    background-color:transparent;\n"
"}")
        self.Buttons.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Buttons.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Buttons.setObjectName("Buttons")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Buttons)
        self.verticalLayout.setObjectName("verticalLayout")
        self.homeBtn = QtWidgets.QFrame(parent=self.Buttons)
        self.homeBtn.setMaximumSize(QtCore.QSize(240, 42))
        self.homeBtn.setStyleSheet("QFrame{\n"
"    width:240px;\n"
"    height:42px;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background-color: #FCD597;\n"
"}")
        self.homeBtn.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.homeBtn.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.homeBtn.setObjectName("homeBtn")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.homeBtn)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.homeBtn)
        self.label_3.setMinimumSize(QtCore.QSize(26, 26))
        self.label_3.setMaximumSize(QtCore.QSize(26, 26))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/Icons/Icons/home.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.pushButton = QtWidgets.QPushButton(parent=self.homeBtn)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background-color: transparent;\n"
"    font-size:14px;\n"
"    font-weight:bold;\n"
"    color: #78B3CE;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.homeBtn)
        self.AddPatientBtn = QtWidgets.QFrame(parent=self.Buttons)
        self.AddPatientBtn.setMaximumSize(QtCore.QSize(240, 42))
        self.AddPatientBtn.setStyleSheet("QFrame{\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background-color: #FCD597;\n"
"}")
        self.AddPatientBtn.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.AddPatientBtn.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.AddPatientBtn.setObjectName("AddPatientBtn")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.AddPatientBtn)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.AddPatientBtn)
        self.label_2.setMinimumSize(QtCore.QSize(28, 28))
        self.label_2.setMaximumSize(QtCore.QSize(28, 28))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Icons/Icons/AddIcon.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.AddPatientBtn)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    font-size:14px;\n"
"    font-weight:bold;\n"
"    color:#78B3CE;\n"
"    \n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.AddPatientBtn)
        self.petDetailsbtn = QtWidgets.QFrame(parent=self.Buttons)
        self.petDetailsbtn.setMaximumSize(QtCore.QSize(240, 42))
        self.petDetailsbtn.setStyleSheet("QFrame{\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background-color: #FCD597;\n"
"}")
        self.petDetailsbtn.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.petDetailsbtn.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.petDetailsbtn.setObjectName("petDetailsbtn")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.petDetailsbtn)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(parent=self.petDetailsbtn)
        self.label_4.setMaximumSize(QtCore.QSize(30, 30))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/Icons/Icons/petDetailsIcon.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.petDetailsbtn)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    font-size:14px;\n"
"    font-weight:bold;\n"
"    color:#78B3CE;\n"
"    \n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.verticalLayout.addWidget(self.petDetailsbtn)
        self.frame_6 = QtWidgets.QFrame(parent=self.Buttons)
        self.frame_6.setMinimumSize(QtCore.QSize(240, 42))
        self.frame_6.setMaximumSize(QtCore.QSize(240, 42))
        self.frame_6.setStyleSheet("QFrame{\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background-color: #FCD597;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_5.setMinimumSize(QtCore.QSize(30, 30))
        self.label_5.setMaximumSize(QtCore.QSize(30, 30))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/Icons/Icons/AppointmentIcon.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    font-size:14px;\n"
"    font-weight:bold;\n"
"    color:#78B3CE;\n"
"    \n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.verticalLayout.addWidget(self.frame_6)
        self.gridLayout_2.addWidget(self.Buttons, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 31, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_2.addItem(spacerItem3, 7, 0, 1, 1)
        self.PetmateLogo = QtWidgets.QLabel(parent=self.sideNav)
        self.PetmateLogo.setMinimumSize(QtCore.QSize(212, 81))
        self.PetmateLogo.setMaximumSize(QtCore.QSize(212, 81))
        self.PetmateLogo.setText("")
        self.PetmateLogo.setPixmap(QtGui.QPixmap(":/Images/image/petmateLogo.png"))
        self.PetmateLogo.setScaledContents(True)
        self.PetmateLogo.setObjectName("PetmateLogo")
        self.gridLayout_2.addWidget(self.PetmateLogo, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.sideNav, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PETMATE INFORMATION SYSTEM"))
        self.pushButton_5.setText(_translate("MainWindow", "LOG OUT"))
        self.pushButton.setText(_translate("MainWindow", "HOME"))
        self.pushButton_2.setText(_translate("MainWindow", "ADD PATIENT"))
        self.pushButton_3.setText(_translate("MainWindow", "PET DETAILS"))
        self.pushButton_4.setText(_translate("MainWindow", "APPOINTMENT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
