# Generated by Django 5.2a1 on 2025-05-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('phoneNumber', models.IntegerField(max_length=11)),
                ('province', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('barangay', models.CharField(max_length=255)),
                ('detailedAddress', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('emergencyNumber', models.IntegerField(max_length=11)),
            ],
        ),
    ]
