# Generated by Django 5.2a1 on 2025-05-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petInfoSys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='emergencyNumber',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='phoneNumber',
            field=models.CharField(max_length=255),
        ),
    ]
