# Generated by Django 5.2.4 on 2025-07-23 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petInfoSys', '0002_alter_basicinfo_emergencynumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petName', models.CharField(max_length=255)),
                ('petColor', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='petInfoSys.basicinfo')),
            ],
        ),
    ]
